version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=cdhlab_dev
      - SQL_USER=cdhlab_dev_user
      - SQL_PASSWORD=yK7zLb3rBbWFCnj
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db
  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cdhlab_dev_user
      - POSTGRES_PASSWORD=yK7zLb3rBbWFCnj
      - POSTGRES_DB=cdhlab_dev

volumes:
  postgres_data:


